### ISSUE TITLE
getAccessories false, name undefined

### ISSUE THREAD

**Issue by matijahardi** [waritsan/arduino-homebridge-mqtt#4]
Hi,
I installed the library and setup an mqtt broker with mosca. I modified the 'SwitchExample' example to work on an esp8266 and tried to make it just turn on and off the builtin led over homebridge. The esp connects to the network and shows up in my router and mosca command line. Homebridge communicates to mosca just fine and everything I configure shows up in the homekit app. For some reason though, the esp does not really talk well to homebridge. Every time I reset the esp (it almost instantly shows up in mosca readout) the homebridge status spits out a 'getAccessories false, name '7893338' undefined. [0]'. I have tried and tried and I can't find any mention of names in the arduino code other than the service name (which I am guessing is for it to get the proper responses from homebridge). Can somebody please help me with this? I have been struggling with this for the past three days :( 

Here's my esp code
`#include <Arduino.h>
#include <ESP8266WiFi.h>
#include "ArduinoHomebridgeMqtt.h"

const IPAddress MQTT_SERVER = IPAddress(192, 168, 8, 109);
const int OUTPUT_PIN = LED_BUILTIN;
const char* SERVICE_NAME = "light";
const char* SERVICE = "Switch";

const char* ssid = "Hardi";
const char* password = "8J9Y0B33378";

ArduinoHomebridgeMqtt arduinoHomebridgeMqtt;

void callback(const char* serviceName, const char* characteristic, int value) {
  if (strcmp(serviceName, SERVICE_NAME) == 0) {
    digitalWrite(OUTPUT_PIN, value);
  }
}

void setup() {
  Serial.begin(9600);
  pinMode(OUTPUT_PIN, OUTPUT);
  WiFi.begin(ssid, password);
  arduinoHomebridgeMqtt.onSetValueFromHomebridge(callback);
  arduinoHomebridgeMqtt.connect(MQTT_SERVER);
  arduinoHomebridgeMqtt.getAccessory();
}

void loop() {
  arduinoHomebridgeMqtt.loop();
}`

Thanks to anyone who tackles this

**Comment by waritsan** [comment]
You have to add the accessory first. In setup() you can add the following line before the call to getAccessory().

```
arduinoHomebridgeMqtt.addAccessory(SERVICE_NAME, SERVICE);
```
